Day.create(date: Date.strptime('2016-08-01', '%Y-%m-%d'))
Day.create(date: Date.strptime('2016-08-02', '%Y-%m-%d'))
Day.create(date: Date.strptime('2016-08-03', '%Y-%m-%d'))
Day.create(date: Date.strptime('2016-08-04', '%Y-%m-%d'))
Day.create(date: Date.strptime('2016-08-05', '%Y-%m-%d'))
Day.create(date: Date.strptime('2016-08-06', '%Y-%m-%d'))
Day.create(date: Date.strptime('2016-08-07', '%Y-%m-%d'))

User.create(name: "Rob D.")
User.create(name: "Elena HS.")
User.create(name: "Lauren F.")
User.create(name: "Joe S.")
User.create(name: "John G.")
User.create(name: "Jonathan M.")
User.create(name: "Erik S.")
User.create(name: "Kyle YK.")
User.create(name: "Christine G.")
User.create(name: "Diane M.")

Event.create(day_id:1, name: "Pay comcast", time: "09:00:00")
Event.create(day_id:1, name: "Lunch with Lauren", time: "12:00:00" )
Event.create(day_id:1, name: "Star Trek", time: "20:00:00")
Event.create(day_id:2, name: "Chicago hack night", time: "18:00:00")
Event.create(day_id:4, name: "Call bank", time: "18:00:00")
Event.create(day_id:4, name: "Date night", time: "18:00:00" )
Event.create(day_id:6, name: "Groceries", time:"12:00:00")
Event.create(day_id:6, name: "Erik's bachelor party", time:"18:00:00")
Event.create(day_id:7, name: "Call mom and dad", time: "17:00:00")
Event.create(day_id:7, name: "Laundry", time:"18:00:00")

Rsvp.create(event_id: 1, user_id: 1, yes_no_maybe: "yes" )
Rsvp.create(event_id: 2, user_id: 1, yes_no_maybe: "yes" )
Rsvp.create(event_id: 2, user_id: 3, yes_no_maybe: "yes" )
Rsvp.create(event_id: 3, user_id: 1, yes_no_maybe: "yes" )
Rsvp.create(event_id: 3, user_id: 2, yes_no_maybe: "yes" )
Rsvp.create(event_id: 3, user_id: 3, yes_no_maybe: "yes" )
Rsvp.create(event_id: 3, user_id: 6, yes_no_maybe: "yes" )
Rsvp.create(event_id: 4, user_id: 1, yes_no_maybe: "yes" )
Rsvp.create(event_id: 4, user_id: 4, yes_no_maybe: "yes" )
Rsvp.create(event_id: 5, user_id: 1, yes_no_maybe: "yes" )
Rsvp.create(event_id: 6, user_id: 1, yes_no_maybe: "yes" )
Rsvp.create(event_id: 6, user_id: 2, yes_no_maybe: "yes" )
Rsvp.create(event_id: 7, user_id: 1, yes_no_maybe: "yes" )
Rsvp.create(event_id: 8, user_id: 1, yes_no_maybe: "yes" )
Rsvp.create(event_id: 8, user_id: 4, yes_no_maybe: "yes" )
Rsvp.create(event_id: 8, user_id: 6, yes_no_maybe: "yes" )
Rsvp.create(event_id: 8, user_id: 7, yes_no_maybe: "yes" )
Rsvp.create(event_id: 8, user_id: 8, yes_no_maybe: "yes" )
Rsvp.create(event_id: 8, user_id: 9, yes_no_maybe: "yes" )
Rsvp.create(event_id: 8, user_id: 10, yes_no_maybe: "yes" )
Rsvp.create(event_id: 9, user_id: 1, yes_no_maybe: "yes" )
Rsvp.create(event_id: 10, user_id: 1, yes_no_maybe: "yes" )
